<?php

namespace Nirbose\PhpMcServ\Entity;

use Nirbose\PhpMcServ\Network\Serializer\PacketSerializer;
use Nirbose\PhpMcServ\World\Position;

class EndCrystal extends Entity
{
    private ?Position $target = null;
    private bool $showBottom = true;

    public function getTarget(): ?Position
    {
        return $this->target;
    }

    public function setTarget(?Position $target): void
    {
        $this->target = $target;
    }

    public function showBottom(): bool
    {
        return $this->showBottom;
    }

    public function setShowBottom(bool $showBottom): void
    {
        $this->showBottom = $showBottom;
    }

    protected function getMetadataPacket(): PacketSerializer
    {
        $packet = parent::getMetadataPacket(); // TODO: Change the autogenerated stub

        // Target
        $packet->putUnsignedByte(8);
        $packet->putVarInt(11);
        if (is_null($this->target)) {
            $packet->putBool(false);
        } else {
            $packet->putBool(true);
            $packet->putPosition($this->target->getX(), $this->target->getY(), $this->target->getZ());
        }

        // Show bottom
        $packet->putUnsignedByte(9);
        $packet->putVarInt(8);
        $packet->putBool($this->showBottom);

        return $packet;
    }

    /**
     * @inheritDoc
     */
    function getType(): EntityType
    {
        return EntityType::END_CRYSTAL;
    }
}