"""
This script generates a 'MobEffectType' PHP enum from the mob effect data
found in the 'registries.json' file.
"""

import json

mob_effect_data = {}

def create_php_enum():
    """
    Creates the 'MobEffectType.php' PHP file with the mob effect enumeration.
    """
    sorted_items = sorted(mob_effect_data.items())

    cases = "\n".join([f"    case {name} = {id};" for id, name in sorted_items])

    enum_string = f"""<?php

// This file is automatically generated. Do not edit manually.

namespace SnapMine\\Effect;

enum MobEffectType: int
{{
{cases}
}}
"""

    with open("MobEffectType.php", "w") as file:
        file.write(enum_string)

def main():
    """
    Main function to load data and generate the enum.
    """
    try:
        with open("registries.json", "r") as f:
            registries = json.load(f)
    except FileNotFoundError:
        print("Error: 'registries.json' not found. Make sure it's in the same directory.")
        return

    mob_effect_entries = registries["minecraft:mob_effect"]["entries"]

    for name, value in mob_effect_entries.items():
        mob_effect_id = value["protocol_id"]

        formatted_name = str(name).replace("minecraft:", "").replace(".", "_").upper()
        mob_effect_data[mob_effect_id] = formatted_name

    create_php_enum()
    print("MobEffectType enum successfully generated in 'MobEffectType.php'.")

if __name__ == "__main__":
    main()