"""
This script generates a 'Sound' PHP enum from the sound data
found in the 'registries.json' file.
"""

import json

sound_data = {}

def create_php_enum():
    """
    Creates the 'Sound.php' PHP file with the sound enumeration.
    """
    sorted_items = sorted(sound_data.items())

    cases = "\n".join([f"    case {name} = {id};" for id, name in sorted_items])

    enum_string = f"""<?php

// This file is automatically generated. Do not edit manually.

namespace Nirbose\\PhpMcServ\\Sound;

enum Sound: int
{{
{cases}
}}
"""

    with open("Sound.php", "w") as file:
        file.write(enum_string)

def main():
    """
    Main function to load data and generate the enum.
    """
    try:
        with open("registries.json", "r") as f:
            registries = json.load(f)
    except FileNotFoundError:
        print("Error: 'registries.json' not found. Make sure it's in the same directory.")
        return

    sound_entries = registries["minecraft:sound_event"]["entries"]

    for name, value in sound_entries.items():
        sound_id = value["protocol_id"]

        formatted_name = str(name).replace("minecraft:", "").replace(".", "_").upper()
        sound_data[sound_id] = formatted_name

    create_php_enum()
    print("Sound enum successfully generated in 'Sound.php'.")

if __name__ == "__main__":
    main()