<?php

// This file is automatically generated. Do not edit manually.

namespace SnapMine\Effect;

enum MobEffectType: int
{
    case SPEED = 0;
    case SLOWNESS = 1;
    case HASTE = 2;
    case MINING_FATIGUE = 3;
    case STRENGTH = 4;
    case INSTANT_HEALTH = 5;
    case INSTANT_DAMAGE = 6;
    case JUMP_BOOST = 7;
    case NAUSEA = 8;
    case REGENERATION = 9;
    case RESISTANCE = 10;
    case FIRE_RESISTANCE = 11;
    case WATER_BREATHING = 12;
    case INVISIBILITY = 13;
    case BLINDNESS = 14;
    case NIGHT_VISION = 15;
    case HUNGER = 16;
    case WEAKNESS = 17;
    case POISON = 18;
    case WITHER = 19;
    case HEALTH_BOOST = 20;
    case ABSORPTION = 21;
    case SATURATION = 22;
    case GLOWING = 23;
    case LEVITATION = 24;
    case LUCK = 25;
    case UNLUCK = 26;
    case SLOW_FALLING = 27;
    case CONDUIT_POWER = 28;
    case DOLPHINS_GRACE = 29;
    case BAD_OMEN = 30;
    case HERO_OF_THE_VILLAGE = 31;
    case DARKNESS = 32;
    case TRIAL_OMEN = 33;
    case RAID_OMEN = 34;
    case WIND_CHARGED = 35;
    case WEAVING = 36;
    case OOZING = 37;
    case INFESTED = 38;
}
