name: Pest workflow

on:
  pull_request:
    types: [opened, reopened]
  push:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5

    - name: Trust repo for Git
      run: git config --global --add safe.directory /app

    - name: Install dependencies
      uses: php-actions/composer@v6
      with:
        php_version: "8.3"
        php_extensions: sockets gmp
        version: 2.x

    - name: Run Pest tests
      run: ./vendor/bin/pest
