name: PHPStan

on:
  pull_request:
    types: [opened, reopened]
  push:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5

    - name: Install dependencies
      uses: php-actions/composer@v6
      with:
        php_version: "8.3"
        php_extensions: sockets gmp
        version: 2.x

    - uses: php-actions/phpstan@v3
      with:
        path: src/